//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by res.rc
//
#define IDR_MENU1                       101
#define IDR_MENU2                       130
#define IDC_STATIC_GRID                 1000
#define IDC_SLIDER1                     1002
#define IDC_SLIDER_GREEN                1003
#define IDC_SLIDER_RED                  1004
#define IDC_LIST_TEXTURENAMES           1010
#define IDC_LOADTEXPACKAGE              1011
#define IDC_APPLYTOCURRENT              1013
#define IDC_STATIC_LEVELPROPERTIES      1024
#define IDC_EDIT_LEVELNAME              1025
#define IDC_EDIT_AUTHORNAME             1026
#define IDC_STATIC_LEVELNAME            1027
#define IDC_STATIC_AUTHORNAME           1028
#define IDC_STATIC_TEXTUREPREVIEW       1031
#define IDC_BUTTON_EDITTEX              1032
#define IDC_BUTTON_SAVE                 1033
#define IDC_BUTTON_IMPORTTEX            1034
#define IDC_BUTTON_EXPORTTEX            1035
#define IDC_STATIC_PREVIEWTEX           1036
#define IDC_RADIO_SINGLEPLAYER          1037
#define IDC_RADIO_DEATHMATCH            1038
#define IDC_RADIO_CAPTURETHEFLAG        1039
#define IDC_RADIO_DOMINATION            1041
#define IDC_STATIC_MAPINFO              1042
#define IDC_RADIO_COOPERATIVE           1043
#define IDC_EDIT_URL                    1045
#define IDC_STATIC_URL                  1046
#define IDC_EDIT2                       1047
#define IDC_STATIC_ENTRYTEXT            1048
#define IDC_STATIC_SINGLEPLAYER         1050
#define IDC_STATIC_DEATHMATCH           1051
#define IDC_STATIC_DOMINATION           1052
#define IDC_STATIC_CAPTURETHEFLAG       1053
#define IDC_STATIC_COOPERATIVE          1054
#define IDC_TREE_POLYGONTREE            1055
#define IDC_STATIC_POLYGONTREE          1056
#define IDC_STATIC_BORDER               1058
#define IDC_EDIT_TEXTUREU               1065
#define IDC_EDIT_TEXTUREV               1066
#define IDC_STATIC_TEXTUREU             1067
#define IDC_STATIC_TEXTUREV             1068
#define IDC_STATIC_RED                  1070
#define IDC_STATIC_GREEN                1071
#define IDC_STATIC_BLUE                 1072
#define IDC_EDIT_RED                    1073
#define IDC_EDIT_GREEN                  1074
#define IDC_EDIT_BLUE                   1075
#define IDC_STATIC_COLORPREVIEW         1077
#define IDC_STATIC_TEXTUREPACKAGE       1091
#define IDC_LIST_PACKAGE                1092
#define IDC_STATIC_TEXTURE              1093
#define IDC_STATIC_NAME                 1094
#define IDC_EDIT_NAME                   1095
#define IDC_BUTTON_APPLYNAME            1096
#define IDC_CHECK_AUTOUPDATE            1098
#define IDC_BUTTON_PANUP                1099
#define IDC_BUTTON_PANDOWN              1100
#define IDC_BUTTON_PANLEFT              1101
#define IDC_BUTTON_PANRIGHT             1102
#define IDC_STATIC_PAN                  1103
#define IDC_BUTTON_FLIPU                1104
#define IDC_BUTTON_FLIPV                1105
#define IDC_EDIT_SCALE                  1106
#define IDC_STATIC_SCALE                1107
#define IDC_CHECK_UPAN                  1110
#define IDC_CHECK_VPAN                  1111
#define IDC_EDIT_PANAMOUNT              1112
#define IDC_CHECK_TRANSLUCENT           1113
#define IDC_STATIC_LIGHTPROPERTIES      1114
#define IDC_SLIDER_BLUE                 1116
#define IDC_STATIC_REDLIGHT             1117
#define IDC_STATIC_GREENLIGHT           1118
#define IDC_STATIC_BLUELIGHT            1119
#define IDC_STATIC_LIGHTCOLOR           1120
#define IDC_STATIC_LIGHTNAME            1121
#define IDC_EDIT_LIGHTNAME              1122
#define IDC_BUTTON_APPLYLIGHTNAME       1123
#define IDC_LIST_LIGHTLIST              1124
#define IDC_CHECK_ENABLELIGHT           1125
#define IDC_BUTTON_POLYGON_ALIGNTEXTURES 1126
#define IDC_BUTTON_FACE_ALIGNTEXTURE    1127
#define IDC_STATIC_BRUSHS               1128
#define IDC_STATIC_BRUSHPROPERTIES      1134
#define IDC_RADIO_SHEET                 1136
#define IDC_RADIO_CUBE                  1137
#define IDC_RADIO_STAIRS                1138
#define IDC_RADIO_SPIRAL                1139
#define IDC_RADIO_CONE                  1140
#define IDC_RADIO_SPHERE                1141
#define IDC_RADIO_CYLINDER              1142
#define IDC_RADIO9                      1143
#define IDC_RADIO_CIRCLE                1143
#define IDC_RADIO10                     1144
#define IDC_BUTTON_ADDBRUSHTOCUSTOM     1149
#define IDC_STATIC_CUSTOMBRUSH          1150
#define IDC_BUTTON_REMOVEBRUSHFROMCUSTOM 1151
#define IDC_LIST1                       1152
#define IDC_EDIT_USIZE                  1160
#define IDC_EDIT_VSIZE                  1162
#define IDC_STATIC_SHEET_U              1163
#define IDC_STATIC_SHEET_VSIZE          1164
#define IDC_STATIC_SHEET_ALIGNEMNT      1165
#define IDC_STATIC_SHEET_SIZE           1166
#define IDC_EDIT_CUBE_LENGTH            1170
#define IDC_EDIT_CUBE_DEPTH             1170
#define IDC_EDIT_CUBE_WIDTH             1171
#define IDC_EDIT_CUBE_HEIGHT            1172
#define IDC_STATIC_CUBE_DIMENSIONS      1173
#define IDC_STATIC_CUBE_LENGTH          1174
#define IDC_STATIC_CUBE_DEPTH           1174
#define IDC_STATIC_WIDTH                1175
#define IDC_STATIC_HEIGHT               1176
#define IDC_STATIC_STEP_DEPTH           1177
#define IDC_STATIC_STEP_WIDTH           1178
#define IDC_STATIC_STEP_HEIGHT          1179
#define IDC_EDIT_STEP_DEPTH             1180
#define IDC_EDIT_STEP_WIDTH             1181
#define IDC_EDIT_STEP_HEIGHT            1182
#define IDC_STATIC_STEP_STEPS           1183
#define IDC_STATIC_STEP_ADDTOFIRST      1184
#define IDC_EDIT_STEP_NUMSTEPS          1185
#define IDC_EDIT_STEP_ADDTOFIRST        1186
#define IDC_STATIC_SPIRAL_WIDTH         1188
#define IDC_STATIC_SPIRAL_HEIGHT        1189
#define IDC_EDIT_SPIRAL_WIDTH           1191
#define IDC_EDIT_SPIRAL_HEIGHT          1192
#define IDC_EDIT_SPIRAL_NUMSTEPS        1193
#define IDC_EDIT_SPIRAL_ADDTOFIRST      1194
#define IDC_STATIC_SPIRAL_ADDTOFIRST    1195
#define IDC_STATIC_SPIRAL_STEPS         1196
#define IDC_STATIC_SPIRAL_DEGREES       1197
#define IDC_BUTTON_UPDATEBRUSH          1197
#define IDC_EDIT_SPIRAL_DEGREES         1198
#define IDC_STATIC_SPIRAL_INNERRADIUS   1199
#define IDC_EDIT_SPIRAL_INNERRADIUS     1200
#define IDC_RADIO_SHEET_X_AXIS          1201
#define IDC_RADIO_SHEET_Y_AXIS          1202
#define IDC_RADIO_SHEET_Z_AXIS          1203
#define IDC_STATIC_EDITOR_OPTIONS       1204
#define IDC_CHECK_UPDATE_POLYS          1205
#define IDC_CHECK_UPDATE_FACES          1206
#define IDC_CHECK_UPDATE_VERTS          1207
#define IDC_BUTTON_APPLYEDITOROPTIONS   1210
#define IDC_STATIC_CALL_FRAMEMOVE       1211
#define IDC_STATIC_RENDER_OPTIONS       1212
#define IDC_CHECK_RENDER_NORMALS        1213
#define IDC_CHECK_RENDER_BRUSH          1214
#define IDC_CHECK_USE_TEXTURING         1215
#define IDC_CHECK_USE_LIGHTING          1216
#define IDC_CHECK_RENDER_SELECTED       1217
#define IDC_CHECK_RENDER_POLYGONS       1218
#define IDC_STATIC_ACTIVE_WINDOWS       1219
#define IDC_CHECK_ACTIVE_XZ             1220
#define IDC_CHECK_ACTIVE_XY             1221
#define IDC_CHECK_ACTIVE_YZ             1222
#define IDC_STATIC_ENABLE               1223
#define IDC_CHECK_ACTIVE_3D             1224
#define IDC_STATIC_CYLINDER_HEIGHT      1225
#define IDC_STATIC_CYLINDER_RADIUS      1226
#define IDC_STATIC_CYLINDER_SIDES       1227
#define IDC_STATIC_CYLINDER_DIMENSIONS  1228
#define IDC_EDIT_CYLINDER_HEIGHT        1229
#define IDC_EDIT_CYLINDER_RADIUS        1230
#define IDC_EDIT_CYLINDER_SIDES         1231
#define IDC_STATIC_DIMENSIONS           1232
#define IDC_STATIC_SIDES                1233
#define IDC_STATIC_RADIUS               1234
#define IDC_EDIT_CIRCLE_SIDES           1235
#define IDC_EDIT_CIRCLE_RADIUS          1236
#define IDC_STATIC_CIRCLE_DEGREES       1237
#define IDC_EDIT_CIRCLE_DEGREES         1238
#define IDC_RADIO_TEXTURE1              1239
#define IDC_RADIO_TEXTURE2              1240
#define IDC_RADIO_LIGHTMAP              1241
#define IDC_STATIC_APPLY_TEXTURE_AS     1242
#define IDC_CHECK_USE_TEXTURE1          1243
#define IDC_CHECK_USE_TEXTURE2          1244
#define IDC_CHECK_USE_LIGHTMAP          1245
#define IDC_BUTTON_CALCULATE_LIGHTMAPS  1246
#define IDC_EDIT_TOTAL_BOUNCES          1249
#define IDC_STATIC_LIGHTMAP_LOD         1250
#define IDC_BUTTON_ROTATE_90            1251
#define IDC_PROGRESS_LIGHTING           1252
#define IDC_STATIC_LIGHTINGPROGRESS     1253
#define IDC_STATIC_LIGHT_PROGRESS       1254
#define IDC_STATIC_LIGHT_CURRENT_POLYGON 1255
#define IDC_STATIC_LIGHT_CURRENT_FACE   1256
#define IDC_STATIC_OF                   1257
#define IDC_EDIT_CURRENT_POLYGON        1258
#define IDC_EDIT_CURRENT_FACE           1259
#define IDC_STATIC_OF2                  1260
#define IDC_EDIT_TOTAL_POLYGONS         1261
#define IDC_EDIT_TOTAL_FACES            1262
#define IDC_EDIT_CURRENT_U              1263
#define IDC_EDIT_CURRENT_V              1264
#define IDC_STATIC_U                    1265
#define IDC_STATIC_V                    1266
#define IDC_STATIC_OF3                  1267
#define IDC_STATIC_LIGHTMAP_RES         1268
#define IDC_EDIT_LIGHTMAP_RES           1269
#define IDC_STATIC_PATCH                1270
#define IDC_EDIT_CURRENT_PATCH          1271
#define IDC_EDIT_CURRENT_TOTAL_PATCHES  1272
#define IDC_EDIT_LIGHT_PERCENT          1273
#define IDC_STATIC_PERCENT              1274
#define IDC_BUTTON_ROTATE_LIGHTMAP      1275
#define IDC_STATIC_REFLECTION_INTENSITY 1276
#define IDC_STATIC_LIGHT_INTENSITY      1277
#define IDC_EDIT_LIGHT_REFLECTION_INTENSITY 1278
#define IDC_EDIT_LIGHT_INTENSITY        1279
#define IDC_CHECK_SHOW_HEMICUBE         1280
#define IDC_STATIC_COLOR                1281
#define IDC_EDIT_LIGHTING_R             1282
#define IDC_EDIT_LIGHTING_G             1283
#define IDC_EDIT_LIGHTING_B             1284
#define IDC_STATIC_LIGHTING_R           1285
#define IDC_STATIC_LIGHTING_G           1286
#define IDC_STATIC_LIGHTING_B           1287
#define IDC_EDIT_LIGHTMAP_THRESHOLD     1288
#define IDC_STATIC_LIGHTMAP_THRESHOLD   1289
#define IDC_CHECK_RENDER_LIGHTS         1290
#define IDC_BUTTON_REMOVE_LIGHT         1292
#define IDC_SLIDER_LIGHT_RED            1293
#define IDC_SLIDER_LIGHT_GREEN          1294
#define IDC_SLIDER_LIGHT_BLUE           1295
#define IDC_STATIC_R                    1296
#define IDC_STATIC_G                    1297
#define IDC_STATIC_B                    1298
#define IDC_STATIC_LIGHT_BRIGHTNESS     1299
#define IDC_SLIDER_LIGHT_INTENSITY      1300
#define IDC_BUTTON_ADD_LIGHT            1301
#define IDC_STATIC_RADIOSITY            1302
#define IDC_STATIC_LIGHT_PROPERTIES     1304
#define IDC_STATIC_LIGHT_NAME           1305
#define IDC_EDIT_LIGHT_NAME             1306
#define IDC_BUTTON_APPLY_LIGHT_NAME     1307
#define IDC_BUTTON_LIGHT_EFFECTS        1308
#define IDC_RADIO_HIGH_QUALITY_LIGHTING 1309
#define IDC_RADIO_NORMAL_QUALITY_LIGHTING 1310
#define IDC_STATIC_GEOMETRY             1311
#define IDC_BUTTON_GEOMETRY_SLIDE_FORWARD 1315
#define IDC_STATIC_MOVE_GEOMETRY        1316
#define IDC_BUTTON_EXPAND_FACE          1317
#define IDC_EDIT_GEOMETRY_MOVE_SCALE    1318
#define IDC_STATIC_GEOMETRY_MOVE_AMOUNT 1319
#define IDC_RADIO_GEOMETRY_POLYGON      1320
#define IDC_RADIO_GEOMETRY_FACE         1321
#define IDC_BUTTON_GEOMETRY_SLIDE_UP    1322
#define IDC_BUTTON_GEOMETRY_SLIDE_BACKWARD 1323
#define IDC_RADIO_GEOMETRY_VERTEX       1324
#define IDC_STATIC_GEOMETRY_APPLY_TO    1325
#define IDC_EDIT_GEOMETRY_EXPAND_AMOUNT 1326
#define IDC_STATIC_GEOMETRY_EXPAND_AMOUNT 1327
#define IDC_BUTTONSDB_NEXTTRIANGLE      1328
#define IDC_BUTTONSDB_NEXTVERTEX        1329
#define IDC_BUTTON_GEOMETRY_SLIDE_LEFT  1330
#define IDC_BUTTONSDB_NEXTFACE          1330
#define IDC_BUTTON_GEOMETRY_SLIDE_INFLATE 1331
#define IDC_BUTTONSDB_EXPANDFACE        1331
#define IDC_BUTTON_GEOMETRY_SLIDE_DEFLATE 1332
#define IDC_BUTTONSDB_NEXTSEGMENT       1332
#define IDC_BUTTONSDB_SUBTRACTBRUSH     1333
#define IDC_BUTTON_GEOMETRY_SLIDE_RIGHT 1334
#define IDC_BUTTONSDB_ADDBRUSH          1334
#define IDC_BUTTON_GEOMETRY_ROTATE_LEFT 1335
#define IDC_BUTTONSDB_SELECTION         1335
#define IDC_BUTTON_GEOMETRY_SLIDE_DOWN  1336
#define IDC_STATIC_BRUSH                1336
#define IDC_BUTTON_GEOMETRY_ROTATE_RIGHT 1337
#define IDC_BUTTONSDB_REBUILD_GEOMETRY  1337
#define ID_EXIT                         40001
#define ID_UNDO                         40002
#define ID_REDO                         40003
#define ID_ADD_VERTEX                   40004
#define ID_DELETE_VERTEX                40005
#define ID_CUT                          40006
#define ID_COPY                         40007
#define ID_PASTE                        40008
#define ID_VERTEX_PROPERTIES            40009
#define ID_DELETE_POLYGON               40010
#define ID_ADD_POLYGON                  40011
#define ID_RESET_POSITION               40012
#define ID_CAMERA_PROPERTIES            40013
#define ID_SAVE_MAP                     40014
#define ID_FILE_SAVEMAPAS               40015
#define ID_NEW                          40016
#define ID_OPEN                         40017
#define ID_CLOSE                        40018
#define ID_SELECT_ALL                   40019
#define ID_LOAD_POLYGON                 40020
#define ID_SAVE_POLYGON                 40021
#define ID_SAVE_AS                      40022
#define ID_MAP_PROPERTIES               40023
#define ID_EDITOR_PROPERTIES            40024
#define ID_ABOUT                        40025
#define ID_BRUSH_MATERIALIZE            40026
#define ID_BRUSH_TRIANGLE               40027
#define ID_BRUSH_CUBE                   40028
#define ID_BRUSH_SHEET                  40029
#define ID_VERTEX_SELECTNEXT            40030
#define ID_TEXTURES_LOADSET             40031
#define ID_WINDOW_RESETVIEWS            40033
#define ID_WINDOW_TOGGLEACTIVESTATE_3DWINDOW 40035
#define ID_WINDOW_TOGGLEACTIVESTATE_2DLEFTWINDOW 40036
#define ID_WINDOW_TOGGLEACTIVESTATE_2DCENTERWINDOW 40037
#define ID_WINDOW_TOGGLEACTIVESTATE_2DRIGHTWINDOW 40038
#define ID_VIEW_BAHS                    40039
#define ID_VIEW_SCHWING                 40040
#define ID_BRUSH_STAIRS                 40041
#define ID_FACE_ALIGNTEXTURE            40042
#define ID_FACE_DELETE                  40043
#define ID_FACE_BLAH                    40044
#define ID_FILE_RUNLEVEL                40045
#define ID_TEXTURES_ALIGNALLTEXTURES    40046
#define ID_VERTEX_COMPUTEVERTEXCONNECTIONS 40047
#define ID_FACE_REMOVECOENCIDINGFACES   40048
#define ID_VERTEX_SNAPVERTSTOGRID       40049

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        131
#define _APS_NEXT_COMMAND_VALUE         40050
#define _APS_NEXT_CONTROL_VALUE         1338
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
